# Generated by Django 5.1.6 on 2025-02-09 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('company_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('sex', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('role', models.TextField()),
                ('status', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to=settings.AUTH_USER_MODEL)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='api.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='FleetHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('content', models.JSONField()),
                ('risk_level', models.TextField()),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='api.fleet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('heart_rate', models.JSONField()),
                ('sleep_duration', models.JSONField()),
                ('respiration_rate', models.JSONField()),
                ('blood_oxygen', models.JSONField()),
                ('bone_density', models.JSONField()),
                ('height', models.JSONField()),
                ('weight', models.JSONField()),
                ('exercise_level', models.JSONField()),
                ('radiation', models.JSONField()),
                ('outside_time', models.JSONField()),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='api.crewmember')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('severity', models.TextField()),
                ('status', models.TextField()),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_problems', to='api.crewmember')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IndividualHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('content', models.JSONField()),
                ('risk_level', models.TextField()),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='api.crewmember')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
